# GPT-2 pretraining setup
{
  ##### gptj_configs, gxh  #####
  "gradient_accumulation_steps": 16,
  "world_size": 8,
  "data_path": "./data/mydataset_text_document",
  #############################
   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   "pipe-parallel-size": 8,    # gxh, 1->8
   "model-parallel-size": 1,
   

   # model setting
   "gpt_j_residual": True,
   "num-layers": 28,    # gxh, 32->28
   "hidden-size": 4096,
   "num-attention-heads": 16,    # gxh, 32->16
   "seq-length": 1024,  # @lsp 2048 -> 1024
   "max-position-embeddings": 2048,
   "norm": "layernorm",
   "pos-emb": "rotary",
   "no-weight-tying": true,

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled-upper-triang-masked-softmax-fusion": false,
   "bias-gelu-fusion": false,


   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.00012,
       "betas": [0.9, 0.999],
       "eps": 1.0e-8,
     }
   },
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": False
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 1,
   "data-impl": "mmap",
   "split": "949,50,1",

   # activation checkpointing
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   # precision settings
   "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train-iters": 320000, 
   #@lsp如果lr-decay-iters is not None num_iters == lr-decay-iters
   "lr-decay-iters": 320000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "save-interval": 10000,
   "eval-interval": 10,
   "eval-iters": 10,

   # logging
   "log-interval": 50,
   "steps_per_print": 1,
   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": true,


   # @lsp interactive, unconditional, input-file
   "text_gen_type": "input-file",
   "num_samples": 3,
   "sample_input_file": input_file.txt,
   # "pipe_partition_method": "type:transformer|mlp"
   "pipe_partition_method": "parameters",
   
}
