# GPT-2 pretraining setup
{
  "gradient_accumulation_steps": 8,
  ##### gptj_configs, gxh  #####
  "gpt_j_residual": true,
  "world_size": 8,
  "global_num_gpus": 8,
  "n_embd": 4096,    
  "layer_norm_epsilon": 0.00001,
  "attn_pdrop": 0.0,
  "resid_pdrop": 0.0,
  "rotary_dim": 64,
  "activation_function": 'gelu_new',
  "scaled_upper_triang_masked_softmax_fusion": false,
  # "data_path": "data/enron/enron_text_document",
  # "data_path": "./data/enron//mydataset_text_document",
  # "data_path": "/nas/lishengping/caiyun_projects/gpt_neox/data/combine_ids",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/small",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/unseen",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/gptj_class_to_class",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/class_to_class_test",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/single_class",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/class7_to_class2/new",
  # "data_path": "/nas/lishengping/caiyun_projects/gpt_neox/other",
  # "data_path": "/nas/lishengping/caiyun_projects/gpt_neox/xiaomeng",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/filter2000/",
  "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/meta_train/",
  # "data_path": "/nas2/lishengping/caiyun_projects/MetaICL/tensorized/small",
  "train_data_path": "data/novel_train_document",
  "valid_data_path": "data/novel_valid_document",
  # "test_data_path": "data/combine/mydataset_test_document",
  "only_eval": false,
  "finetune": true,
  # 生成的时候为非icl
  "icl_or_neo": "icl",
  "output_layer_parallelism": "column",
  #############################
   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   "pipe-parallel-size": 8,    # gxh, 1->8
   "model-parallel-size": 1,
   

   # model settings
   "num-layers": 28,    # gxh, 32->28
   "hidden-size": 4096,
   "num-attention-heads": 16,    # gxh, 32->16
   "seq-length": 1024,  # @lsp 2048 -> 1024
   "max-position-embeddings": 2048,
   "norm": "layernorm",
   "pos-emb": "rotary",
   "no-weight-tying": true,

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled-upper-triang-masked-softmax-fusion": false,
   "bias-gelu-fusion": false,


   # optimizer settings
   "optimizer": {
     "type": "adam",
     "params": {
       "lr": 0.000001,
       "betas": [0.9, 0.995],
       "eps": 1.0e-8,
     }
   },
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": False
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 1,
   "data-impl": "mmap",
   "split": "949,50,1",

   # activation checkpointing
   "checkpoint-activations": True,
   "checkpoint-num-layers": 1,
   "partition-activations": True,
   "synchronize-each-layer": True,

   # regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   # precision settings
# precision settings
  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1250,
    "initial_scale_power": 0, #lsp 1 -> 0, 初始loss_scale 2 ** 0
    "hysteresis": 2,
    "min_loss_scale": 1
    },
  
  # "soft_prompt_tuning": {},
   # misc. training settings
   "train-iters": 40000, 
   #@lsp如果lr-decay-iters is not None num_iters == lr-decay-iters
   "lr-decay-iters": 40000,
   "distributed-backend": "nccl",
   "lr-decay-style": "linear",
   "warmup": 0.0,
   "save-interval": 5000,
   "eval-interval": 500,
   "eval-iters": 50,

   # logging
   "log-interval": 50,
   "steps_per_print": 1,
   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": true,


   # @lsp interactive, unconditional, input-file
  # "pipe_partition_method": "type:transformer|mlp",
  "pipe_partition_method": "parameters",
  # @lsp 140 -> 180 neox和gptj词表大小不同, 50257 -> 50400，为什么是180，是里面有个词表添加数量计算函数
  "make_vocab_size_divisible_by": 180,
}
